config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/about'
  get 'pages/contact'
  resources :lost_items
  resources :categories
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :lost_items
end

app/models/lost_item.rb
class LostItem < ApplicationRecord
  # belongs_to :category
  # belongs_to :found_by
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :lost_items
	def name
		self.email.split("@")[0]
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_item
  before_action :set_category
  layout :layout_by_activeness

def after_sign_in_path_for(resource_or_scope)
  lost_items_path
end
  protected

  def set_item
  	@item = LostItem.where(@item_id)
  end

  def set_category
  	@category = Category.where(@category_id)
  end

private

def layout_by_activeness
  if devise_controller?
     'application'
  else
     'application'
  end
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, only: [:index, :show]

  
  
  def index
    @categories = Category.all
  end


  def show
  end

 
  def new
    @category = Category.new
  end

 
  def edit
  end

 
  def create
    @category = Category.new(category_params)
    
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.where(@category_id)
    end
    
end

app/controllers/lost_items_controller.rb
class LostItemsController < ApplicationController
  before_action :set_item, :set_category, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @items = LostItem.all
  end


  def show
  end

 
  def new
    @item = LostItem.new
    @category = Category.all.collect { |c| [c.name, c.id]}
  end

 
  def edit

    @category = Category.all.collect { |c| [c.name, c.id]}
  end

  def create

    @item = current_user.lost_items.build(item_params)
    @item.user_id = current_user.id
    @item.category_id = params[:category_id]
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'LostItem was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'LostItem was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to lost_items_url, notice: 'LostItem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = current_user.lost_items.find(params[:id])
    end

    def item_params
      params.require(:lost_item).permit(:name, :category_id)
    end

    def set_category
      @categories = Category.where(@category_id)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :authenticate_user!, only: [:about, :home, :contact]
	def about
	end

	def home
	end

	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lost_items_helper.rb
module LostItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, html: { class: 'form-horizontal' }) do |f| %>
<% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
	<%= f.input :name %><br />
</div>
<div class="field">
	<%= f.submit class: "btn btn-success" %>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1>Update Item</h1>

<%= render 'form' %>

<%= link_to 'Back', lost_items_path %>

app/views/categories/index.html.erb
<h1 style="text-align: center;">Categories</h1>
<% @categories.each do |cat| %>
	<%= cat.name %>
<% end %> 
</div>

app/views/categories/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', lost_items_path %>

app/views/categories/show.html.erb
<h2 class="title text-center"><%= @category.name %></h2>                       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lostnfound</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'pages/navbar' %>
  <div class="container">
    <%= yield %>
    <%= render 'pages/footer' %>
  </div>
  </body> 
</html>

app/views/layouts/index.html.erb
\<!DOCTYPE html>
<html>
  <head>
    <title>Lostnfound</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', 'style', 'flexslider', 'component', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'simpleCart.min', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'pages/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
  </body> 
</html>

app/views/lost_items/_form.html.erb
<%= simple_form_for @item do |f| %>
<% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
	<%= f.input :name %><br />
</div>

<div class="field">
  <%= select_tag(:category_id, options_from_collection_for_select(Category.all, :id, :name), :prompt => 'select category') %><br />
</div> 
<div class="field">
	<%= f.submit class: "btn btn-success" %>
</div>


<% end %>

app/views/lost_items/edit.html.erb
<h1>Update Item</h1>

<%= render 'form' %>

<%= link_to 'Back', lost_items_path %>

app/views/lost_items/index.html.erb
<div class="row">
<div class="shop col-md-12" style="padding: 40px 20px 40px 300px ;">
	<%= link_to "FOUND A MISPLACED ITEM? POST IT HERE", new_lost_item_path %> 
</div>
<% @items.each do |i|  %>
	<div class="col-md-3 show">
		<p><em><b>Item name:</b></em> <%= i.name %></p>
		<p><em><b>It was found at:</b></em> <%= i.updated_at || i.created_at %></p>
	</div>
<% end %>
</div>

app/views/lost_items/new.html.erb
<!-- <h1 style="padding-top: 15px;">New Item</h1> -->

<%= render 'form' %>

<%= link_to 'Back', lost_items_path %>

app/views/lost_items/show.html.erb
<div class="row">
	<div class="col-md-4 show">
		<p><em><b>Item name:</em></b> <%= @item.name %></p>
		<p><em><b>Item was found by:</b></em> <%= @item.user.name %></p>
		<p><em><b>At:</b></em> <%=  @item.updated_at || @item.created_at %></p>
	</div>
</div>

app/views/pages/_banner.html.erb
<div class="banner">
<div class="container">
<div class="banner-bottom">
	<div class="banner-bottom-left">
		<h2>Lost<br>&<br>Found</h2>
	</div>
	<div class="banner-bottom-right">
		<div  class="callbacks_container">
					<ul class="rslides" id="slider4">
					<li>
								<div class="banner-info">
									<h3>Track lost items</h3>
									<p>Worried you've lost anything...?</p>
									<p>
									<% if user_signed_in? %>
										<%= link_to "FIND", lost_items_path, :class => "btn btn-primary" %> your lost item now...
									<% else %>
										<%= link_to "LOGIN", new_user_session_path, :class => "btn btn-primary" %> | 
										<%= link_to "SIGN UP", new_user_registration_path, :class => "btn btn-primary" %> to find your lost item now...</p>
									<% end %>
								</div>
							</li>
							<li>
								<div class="banner-info">
								  <h3>Found a misplaced item ...? </h3>
									<p>Advertise it here ...</p>
								</div>								
							</li>
						</ul>
					</div>
					<!--banner-->			   
	</div>
	<div class="clearfix"> </div>
</div>
	<div class="shop">
		<%= link_to "GET STARTED", new_user_registration_path %> 
	</div>
	</div>
		</div>

app/views/pages/_footer.html.erb
<div class="footer">
<div class="container">
 <div class="footer_top">
 </div>
<div class="copyright text-center">
	<p>© 2017 VICTOR TURUTHI | Design by   <p> E020-01-0636/2013</p>
</div>
</div>
</div>

app/views/pages/_navbar.html.erb
<!-- header-section-starts -->
	<div class="header">
		<div class="header-top-strip">
			<div class="container">
				<div class="header-top-left">
					<ul>
						<% if !user_signed_in? %>
						<li><%= link_to "Login", new_user_session_path %><span class="glyphicon glyphicon-user"> </span></li>
						<% else %>
						<li><%= link_to "Logout", destroy_user_session_path, method: :delete%><span class="glyphicon glyphicon-user"> </span></li>
						<% end %>
						<li><%= link_to "Register", new_user_registration_path %> <span class="glyphicon glyphicon-lock"> </span></li>			
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- header-section-ends -->
			<div class="banner-top">
		<div class="container">
				<nav class="navbar navbar-default" role="navigation">
	    <div class="navbar-header">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
	        </button>
				<div class="logo">
					<h1><%= link_to "LostNFound", root_path %></h1>
				</div>
	    </div>
	    <!--/.navbar-header-->
	
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	        <ul class="nav navbar-nav">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", pages_about_path %></li>
			<li><%= link_to "contact", pages_contact_path %></li>
	        </ul>
	    </div>
	    <!--/.navbar-collapse-->
	</nav>
	<!--/.navbar-->
</div>
</div>

app/views/pages/about.html.erb
<div class="row">
<div class="col-md-10" style="padding: 40px 60px 0 150px; font-size: 35px; font-family: sans-serif;">
<p><em>We help find lost misplaced items, free of charge</em></p>
<p>COOL, RIGHT!!</p>
<p>yea, help someone find his or her lost item by <br /></p>
</div>
<div class="col-md-12" style="padding: 50px 0px 50px 400px;">
<%= link_to "POSTING IT HERE", new_lost_item_path, :class => "btn btn-primary btn-lg" %>
</p></div>
</div>

app/views/pages/contact.html.erb
<!-- contact-page -->
<div class="contact">
	<div class="container">
			<div class="contact-info">
			<h2>FIND US HERE</h2>
		</div>
		<div class="contact-map">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6632.248000703498!2d151.265683!3d-33.7832959!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b12abc7edcbeb07%3A0x5017d681632bfc0!2sManly+Vale+NSW+2093%2C+Australia!5e0!3m2!1sen!2sin!4v1433329298259" style="border:0"></iframe>
		</div>
		<div class="contact-form">
			<div class="contact-info">
				<h3>CONTACT FORM</h3>
			</div>
			<form>
				<div class="contact-left">
					<input type="text" placeholder="Name" required>
					<input type="text" placeholder="E-mail" required>
					<input type="text" placeholder="Subject" required>
				</div>
				<div class="contact-right">
					<textarea placeholder="Message" required></textarea>
				</div>
				<div class="clearfix"></div>
				<input type="submit" value="SUBMIT">
			</form>
		</div>
	</div>
</div>
<!-- //contact-page -->

	

app/views/pages/home.html.erb
<%= render partial: 'banner' %>